// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1247095039;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_nomikai',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiSimplePushAudioFrame({required List<int> frameBytes});

  Future<void> crateApiSimplePushHevcFrame({
    required List<int> frameBytes,
    required bool isKeyframe,
  });

  Stream<UiEvent> crateApiSimpleStartSankakuReceiver({
    required String bindAddr,
    required List<int> graphBytes,
  });

  Stream<UiEvent> crateApiSimpleStartSankakuSender({
    required String dest,
    required List<int> graphBytes,
  });

  Future<void> crateApiSimpleStopSankakuSender();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiSimplePushAudioFrame({required List<int> frameBytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(frameBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimplePushAudioFrameConstMeta,
        argValues: [frameBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePushAudioFrameConstMeta =>
      const TaskConstMeta(
        debugName: "push_audio_frame",
        argNames: ["frameBytes"],
      );

  @override
  Future<void> crateApiSimplePushHevcFrame({
    required List<int> frameBytes,
    required bool isKeyframe,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(frameBytes, serializer);
          sse_encode_bool(isKeyframe, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimplePushHevcFrameConstMeta,
        argValues: [frameBytes, isKeyframe],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePushHevcFrameConstMeta =>
      const TaskConstMeta(
        debugName: "push_hevc_frame",
        argNames: ["frameBytes", "isKeyframe"],
      );

  @override
  Stream<UiEvent> crateApiSimpleStartSankakuReceiver({
    required String bindAddr,
    required List<int> graphBytes,
  }) {
    final sink = RustStreamSink<UiEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_ui_event_Sse(sink, serializer);
            sse_encode_String(bindAddr, serializer);
            sse_encode_list_prim_u_8_loose(graphBytes, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSimpleStartSankakuReceiverConstMeta,
          argValues: [sink, bindAddr, graphBytes],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleStartSankakuReceiverConstMeta =>
      const TaskConstMeta(
        debugName: "start_sankaku_receiver",
        argNames: ["sink", "bindAddr", "graphBytes"],
      );

  @override
  Stream<UiEvent> crateApiSimpleStartSankakuSender({
    required String dest,
    required List<int> graphBytes,
  }) {
    final sink = RustStreamSink<UiEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_ui_event_Sse(sink, serializer);
            sse_encode_String(dest, serializer);
            sse_encode_list_prim_u_8_loose(graphBytes, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 5,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSimpleStartSankakuSenderConstMeta,
          argValues: [sink, dest, graphBytes],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleStartSankakuSenderConstMeta =>
      const TaskConstMeta(
        debugName: "start_sankaku_sender",
        argNames: ["sink", "dest", "graphBytes"],
      );

  @override
  Future<void> crateApiSimpleStopSankakuSender() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleStopSankakuSenderConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStopSankakuSenderConstMeta =>
      const TaskConstMeta(debugName: "stop_sankaku_sender", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<UiEvent> dco_decode_StreamSink_ui_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  UiEvent dco_decode_ui_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return UiEvent_Log(msg: dco_decode_String(raw[1]));
      case 1:
        return UiEvent_ConnectionState(
          state: dco_decode_String(raw[1]),
          detail: dco_decode_String(raw[2]),
        );
      case 2:
        return UiEvent_HandshakeInitiated();
      case 3:
        return UiEvent_HandshakeComplete(
          sessionId: dco_decode_u_64(raw[1]),
          bootstrapMode: dco_decode_String(raw[2]),
        );
      case 4:
        return UiEvent_Progress(
          streamId: dco_decode_u_32(raw[1]),
          frameIndex: dco_decode_u_64(raw[2]),
          bytes: dco_decode_u_64(raw[3]),
          frames: dco_decode_u_64(raw[4]),
        );
      case 5:
        return UiEvent_Telemetry(
          name: dco_decode_String(raw[1]),
          value: dco_decode_u_64(raw[2]),
        );
      case 6:
        return UiEvent_FrameDrop(
          streamId: dco_decode_u_32(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 7:
        return UiEvent_Fault(
          code: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 8:
        return UiEvent_BitrateChanged(bitrateBps: dco_decode_u_32(raw[1]));
      case 9:
        return UiEvent_VideoFrameReceived(
          data: dco_decode_list_prim_u_8_strict(raw[1]),
        );
      case 10:
        return UiEvent_AudioFrameReceived(
          data: dco_decode_list_prim_u_8_strict(raw[1]),
        );
      case 11:
        return UiEvent_Error(msg: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<UiEvent> sse_decode_StreamSink_ui_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  UiEvent sse_decode_ui_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_msg = sse_decode_String(deserializer);
        return UiEvent_Log(msg: var_msg);
      case 1:
        var var_state = sse_decode_String(deserializer);
        var var_detail = sse_decode_String(deserializer);
        return UiEvent_ConnectionState(state: var_state, detail: var_detail);
      case 2:
        return UiEvent_HandshakeInitiated();
      case 3:
        var var_sessionId = sse_decode_u_64(deserializer);
        var var_bootstrapMode = sse_decode_String(deserializer);
        return UiEvent_HandshakeComplete(
          sessionId: var_sessionId,
          bootstrapMode: var_bootstrapMode,
        );
      case 4:
        var var_streamId = sse_decode_u_32(deserializer);
        var var_frameIndex = sse_decode_u_64(deserializer);
        var var_bytes = sse_decode_u_64(deserializer);
        var var_frames = sse_decode_u_64(deserializer);
        return UiEvent_Progress(
          streamId: var_streamId,
          frameIndex: var_frameIndex,
          bytes: var_bytes,
          frames: var_frames,
        );
      case 5:
        var var_name = sse_decode_String(deserializer);
        var var_value = sse_decode_u_64(deserializer);
        return UiEvent_Telemetry(name: var_name, value: var_value);
      case 6:
        var var_streamId = sse_decode_u_32(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return UiEvent_FrameDrop(streamId: var_streamId, reason: var_reason);
      case 7:
        var var_code = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return UiEvent_Fault(code: var_code, message: var_message);
      case 8:
        var var_bitrateBps = sse_decode_u_32(deserializer);
        return UiEvent_BitrateChanged(bitrateBps: var_bitrateBps);
      case 9:
        var var_data = sse_decode_list_prim_u_8_strict(deserializer);
        return UiEvent_VideoFrameReceived(data: var_data);
      case 10:
        var var_data = sse_decode_list_prim_u_8_strict(deserializer);
        return UiEvent_AudioFrameReceived(data: var_data);
      case 11:
        var var_msg = sse_decode_String(deserializer);
        return UiEvent_Error(msg: var_msg);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_ui_event_Sse(
    RustStreamSink<UiEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_ui_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_ui_event(UiEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case UiEvent_Log(msg: final msg):
        sse_encode_i_32(0, serializer);
        sse_encode_String(msg, serializer);
      case UiEvent_ConnectionState(state: final state, detail: final detail):
        sse_encode_i_32(1, serializer);
        sse_encode_String(state, serializer);
        sse_encode_String(detail, serializer);
      case UiEvent_HandshakeInitiated():
        sse_encode_i_32(2, serializer);
      case UiEvent_HandshakeComplete(
        sessionId: final sessionId,
        bootstrapMode: final bootstrapMode,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_u_64(sessionId, serializer);
        sse_encode_String(bootstrapMode, serializer);
      case UiEvent_Progress(
        streamId: final streamId,
        frameIndex: final frameIndex,
        bytes: final bytes,
        frames: final frames,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_u_32(streamId, serializer);
        sse_encode_u_64(frameIndex, serializer);
        sse_encode_u_64(bytes, serializer);
        sse_encode_u_64(frames, serializer);
      case UiEvent_Telemetry(name: final name, value: final value):
        sse_encode_i_32(5, serializer);
        sse_encode_String(name, serializer);
        sse_encode_u_64(value, serializer);
      case UiEvent_FrameDrop(streamId: final streamId, reason: final reason):
        sse_encode_i_32(6, serializer);
        sse_encode_u_32(streamId, serializer);
        sse_encode_String(reason, serializer);
      case UiEvent_Fault(code: final code, message: final message):
        sse_encode_i_32(7, serializer);
        sse_encode_String(code, serializer);
        sse_encode_String(message, serializer);
      case UiEvent_BitrateChanged(bitrateBps: final bitrateBps):
        sse_encode_i_32(8, serializer);
        sse_encode_u_32(bitrateBps, serializer);
      case UiEvent_VideoFrameReceived(data: final data):
        sse_encode_i_32(9, serializer);
        sse_encode_list_prim_u_8_strict(data, serializer);
      case UiEvent_AudioFrameReceived(data: final data):
        sse_encode_i_32(10, serializer);
        sse_encode_list_prim_u_8_strict(data, serializer);
      case UiEvent_Error(msg: final msg):
        sse_encode_i_32(11, serializer);
        sse_encode_String(msg, serializer);
    }
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
