// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1694417665;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_nomikai',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleInitApp();

  Stream<UiEvent> crateApiSimpleRecvFiles({
    required String bindAddr,
    required String outDir,
    required String pskHex,
  });

  Stream<UiEvent> crateApiSimpleSendFiles({
    required String dest,
    required List<String> relayRoutes,
    required String pskHex,
    required List<String> filePaths,
    required double redundancy,
    required BigInt maxBytesPerSec,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Stream<UiEvent> crateApiSimpleRecvFiles({
    required String bindAddr,
    required String outDir,
    required String pskHex,
  }) {
    final sink = RustStreamSink<UiEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_ui_event_Sse(sink, serializer);
            sse_encode_String(bindAddr, serializer);
            sse_encode_String(outDir, serializer);
            sse_encode_String(pskHex, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSimpleRecvFilesConstMeta,
          argValues: [sink, bindAddr, outDir, pskHex],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleRecvFilesConstMeta => const TaskConstMeta(
    debugName: "recv_files",
    argNames: ["sink", "bindAddr", "outDir", "pskHex"],
  );

  @override
  Stream<UiEvent> crateApiSimpleSendFiles({
    required String dest,
    required List<String> relayRoutes,
    required String pskHex,
    required List<String> filePaths,
    required double redundancy,
    required BigInt maxBytesPerSec,
  }) {
    final sink = RustStreamSink<UiEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_ui_event_Sse(sink, serializer);
            sse_encode_String(dest, serializer);
            sse_encode_list_String(relayRoutes, serializer);
            sse_encode_String(pskHex, serializer);
            sse_encode_list_String(filePaths, serializer);
            sse_encode_f_32(redundancy, serializer);
            sse_encode_u_64(maxBytesPerSec, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSimpleSendFilesConstMeta,
          argValues: [
            sink,
            dest,
            relayRoutes,
            pskHex,
            filePaths,
            redundancy,
            maxBytesPerSec,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleSendFilesConstMeta => const TaskConstMeta(
    debugName: "send_files",
    argNames: [
      "sink",
      "dest",
      "relayRoutes",
      "pskHex",
      "filePaths",
      "redundancy",
      "maxBytesPerSec",
    ],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<UiEvent> dco_decode_StreamSink_ui_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  UiEvent dco_decode_ui_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return UiEvent_Log(msg: dco_decode_String(raw[1]));
      case 1:
        return UiEvent_HandshakeInitiated();
      case 2:
        return UiEvent_HandshakeComplete();
      case 3:
        return UiEvent_FileDetected(
          streamId: dco_decode_u_32(raw[1]),
          traceId: dco_decode_u_64(raw[2]),
          name: dco_decode_String(raw[3]),
          size: dco_decode_u_64(raw[4]),
        );
      case 4:
        return UiEvent_Progress(
          streamId: dco_decode_u_32(raw[1]),
          traceId: dco_decode_u_64(raw[2]),
          current: dco_decode_u_64(raw[3]),
          total: dco_decode_u_64(raw[4]),
        );
      case 5:
        return UiEvent_TransferComplete(
          streamId: dco_decode_u_32(raw[1]),
          traceId: dco_decode_u_64(raw[2]),
          path: dco_decode_String(raw[3]),
        );
      case 6:
        return UiEvent_EarlyTermination(
          streamId: dco_decode_u_32(raw[1]),
          traceId: dco_decode_u_64(raw[2]),
        );
      case 7:
        return UiEvent_Fault(
          code: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 8:
        return UiEvent_Metric(
          name: dco_decode_String(raw[1]),
          value: dco_decode_u_64(raw[2]),
        );
      case 9:
        return UiEvent_Error(msg: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<UiEvent> sse_decode_StreamSink_ui_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  UiEvent sse_decode_ui_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_msg = sse_decode_String(deserializer);
        return UiEvent_Log(msg: var_msg);
      case 1:
        return UiEvent_HandshakeInitiated();
      case 2:
        return UiEvent_HandshakeComplete();
      case 3:
        var var_streamId = sse_decode_u_32(deserializer);
        var var_traceId = sse_decode_u_64(deserializer);
        var var_name = sse_decode_String(deserializer);
        var var_size = sse_decode_u_64(deserializer);
        return UiEvent_FileDetected(
          streamId: var_streamId,
          traceId: var_traceId,
          name: var_name,
          size: var_size,
        );
      case 4:
        var var_streamId = sse_decode_u_32(deserializer);
        var var_traceId = sse_decode_u_64(deserializer);
        var var_current = sse_decode_u_64(deserializer);
        var var_total = sse_decode_u_64(deserializer);
        return UiEvent_Progress(
          streamId: var_streamId,
          traceId: var_traceId,
          current: var_current,
          total: var_total,
        );
      case 5:
        var var_streamId = sse_decode_u_32(deserializer);
        var var_traceId = sse_decode_u_64(deserializer);
        var var_path = sse_decode_String(deserializer);
        return UiEvent_TransferComplete(
          streamId: var_streamId,
          traceId: var_traceId,
          path: var_path,
        );
      case 6:
        var var_streamId = sse_decode_u_32(deserializer);
        var var_traceId = sse_decode_u_64(deserializer);
        return UiEvent_EarlyTermination(
          streamId: var_streamId,
          traceId: var_traceId,
        );
      case 7:
        var var_code = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return UiEvent_Fault(code: var_code, message: var_message);
      case 8:
        var var_name = sse_decode_String(deserializer);
        var var_value = sse_decode_u_64(deserializer);
        return UiEvent_Metric(name: var_name, value: var_value);
      case 9:
        var var_msg = sse_decode_String(deserializer);
        return UiEvent_Error(msg: var_msg);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_ui_event_Sse(
    RustStreamSink<UiEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_ui_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_ui_event(UiEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case UiEvent_Log(msg: final msg):
        sse_encode_i_32(0, serializer);
        sse_encode_String(msg, serializer);
      case UiEvent_HandshakeInitiated():
        sse_encode_i_32(1, serializer);
      case UiEvent_HandshakeComplete():
        sse_encode_i_32(2, serializer);
      case UiEvent_FileDetected(
        streamId: final streamId,
        traceId: final traceId,
        name: final name,
        size: final size,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_u_32(streamId, serializer);
        sse_encode_u_64(traceId, serializer);
        sse_encode_String(name, serializer);
        sse_encode_u_64(size, serializer);
      case UiEvent_Progress(
        streamId: final streamId,
        traceId: final traceId,
        current: final current,
        total: final total,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_u_32(streamId, serializer);
        sse_encode_u_64(traceId, serializer);
        sse_encode_u_64(current, serializer);
        sse_encode_u_64(total, serializer);
      case UiEvent_TransferComplete(
        streamId: final streamId,
        traceId: final traceId,
        path: final path,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_u_32(streamId, serializer);
        sse_encode_u_64(traceId, serializer);
        sse_encode_String(path, serializer);
      case UiEvent_EarlyTermination(
        streamId: final streamId,
        traceId: final traceId,
      ):
        sse_encode_i_32(6, serializer);
        sse_encode_u_32(streamId, serializer);
        sse_encode_u_64(traceId, serializer);
      case UiEvent_Fault(code: final code, message: final message):
        sse_encode_i_32(7, serializer);
        sse_encode_String(code, serializer);
        sse_encode_String(message, serializer);
      case UiEvent_Metric(name: final name, value: final value):
        sse_encode_i_32(8, serializer);
        sse_encode_String(name, serializer);
        sse_encode_u_64(value, serializer);
      case UiEvent_Error(msg: final msg):
        sse_encode_i_32(9, serializer);
        sse_encode_String(msg, serializer);
    }
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
