// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`

/// Asynchronous function that runs the Kyu2 sender engine and streams events back to Dart
Stream<UiEvent> sendFiles({
  required String dest,
  required List<String> relayRoutes,
  required String pskHex,
  required List<String> filePaths,
  required double redundancy,
  required BigInt maxBytesPerSec,
}) => RustLib.instance.api.crateApiSimpleSendFiles(
  dest: dest,
  relayRoutes: relayRoutes,
  pskHex: pskHex,
  filePaths: filePaths,
  redundancy: redundancy,
  maxBytesPerSec: maxBytesPerSec,
);

/// Asynchronous function that runs the Kyu2 receiver engine and streams events back to Dart
Stream<UiEvent> recvFiles({
  required String bindAddr,
  required String outDir,
  required String pskHex,
}) => RustLib.instance.api.crateApiSimpleRecvFiles(
  bindAddr: bindAddr,
  outDir: outDir,
  pskHex: pskHex,
);

@freezed
sealed class UiEvent with _$UiEvent {
  const UiEvent._();

  const factory UiEvent.log({required String msg}) = UiEvent_Log;
  const factory UiEvent.handshakeInitiated() = UiEvent_HandshakeInitiated;
  const factory UiEvent.handshakeComplete() = UiEvent_HandshakeComplete;
  const factory UiEvent.fileDetected({
    required int streamId,
    required BigInt traceId,
    required String name,
    required BigInt size,
  }) = UiEvent_FileDetected;
  const factory UiEvent.progress({
    required int streamId,
    required BigInt traceId,
    required BigInt current,
    required BigInt total,
  }) = UiEvent_Progress;
  const factory UiEvent.transferComplete({
    required int streamId,
    required BigInt traceId,
    required String path,
  }) = UiEvent_TransferComplete;
  const factory UiEvent.earlyTermination({
    required int streamId,
    required BigInt traceId,
  }) = UiEvent_EarlyTermination;
  const factory UiEvent.fault({required String code, required String message}) =
      UiEvent_Fault;
  const factory UiEvent.metric({required String name, required BigInt value}) =
      UiEvent_Metric;
  const factory UiEvent.error({required String msg}) = UiEvent_Error;
}
